import type { GetStaticProps } from "next";
import Head from "next/head";
import Banner from "../components/banner";
import Footer from "../components/footer";
import Header from "../components/header";
import LargeCard from "../components/large_card";
import MediumCard from "../components/medium_card";
import SmallCard from "../components/small_card";
import { MediumCardContent, SmallCardContent } from "../interfaces";
import { motion } from "framer-motion";

type Props = {
    nearbyData?: SmallCardContent[];
    liveAnywhereData?: MediumCardContent[];
};

const Home = ({ nearbyData, liveAnywhereData }: Props) => {
    return (
        <div>
            <Head>
                <title>Airbnb Clone</title>
                <meta
                    name="description"
                    content="An Airbnb clone generated by Nextjs, TailwindCSS and TypeScript"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header transparent={true} placeholder={null} />
            <Banner />
            <main className="max-w-7xl mx-auto px-8 md:px-16">
                <motion.section
                    className="pt-8"
                    initial={{ y: -10, opacity: 0 }}
                    whileInView={{ y: 0, opacity: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.2, duration: 0.8, ease: "easeIn" }}
                >
                    <h2 className="text-4xl font-semibold pb-5">
                        Explore Nearby
                    </h2>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                        {nearbyData?.map((nearby) => (
                            <SmallCard key={nearby.image} data={nearby} />
                        ))}
                    </div>
                </motion.section>
                <motion.section
                    className="pt-8"
                    initial={{ y: -10, opacity: 0 }}
                    whileInView={{ y: 0, opacity: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.8, ease: "easeIn" }}
                >
                    <h2 className="text-4xl font-semibold pb-5">
                        Live Anywhere
                    </h2>
                    <div className="flex space-x-6 overflow-scroll scrollbar-hide p-3 -ml-3">
                        {liveAnywhereData?.map((liveAnywhere) => (
                            <MediumCard
                                key={liveAnywhere.image}
                                data={liveAnywhere}
                            />
                        ))}
                    </div>
                </motion.section>
                <LargeCard
                    data={{
                        image: "https://firebasestorage.googleapis.com/v0/b/test-e9746.appspot.com/o/large1.webp?alt=media&token=e90317b9-d58d-4394-acfd-5d1b3463f2d4",
                        title: "The Greatest Outdoors",
                        description: "Wishlists curated by Airbnb.",
                        buttonText: "Get Inspired",
                    }}
                />
            </main>
            <Footer />
        </div>
    );
};

export const getStaticProps: GetStaticProps = async () => {
    const nearbyData: SmallCardContent[] = await fetch(
        "https://test-e9746-default-rtdb.firebaseio.com/airbnb/nearby.json"
    ).then((res) => res.json());

    const liveAnywhereData: MediumCardContent[] = await fetch(
        "https://test-e9746-default-rtdb.firebaseio.com/airbnb/live_anywhere.json"
    ).then((res) => res.json());

    return {
        props: { nearbyData, liveAnywhereData },
    };
};

export default Home;
